### ISSUE TITLE
Possible race-condition when first using the WARC writers?

### ISSUE THREAD

**Issue by anjackson** [internetarchive/heritrix3#167]
Most of the times I start a crawl using a recent Heritrix build, an exception gets thrown when the system first tries to write to a WARC file. e.g.

```
2016-08-12T09:06:35.096Z    -5         54 dns:madebybridge.com RLP http://madebybridge.com/ text/dns #030 20160812090634493+63 sha1:QT62S24FK6C32Z7PBBYEDY3OBTNBZFMI - err=java.lang.NullPointerException
 java.lang.NullPointerException
        at org.archive.io.warc.WARCWriter.getFilenameWithoutOccupiedSuffix(WARCWriter.java:275)
        at org.archive.modules.writer.WARCWriterProcessor.updateMetadataAfterWrite(WARCWriterProcessor.java:289)
        at org.archive.modules.writer.WARCWriterProcessor.write(WARCWriterProcessor.java:259)
        at org.archive.modules.writer.WARCWriterProcessor.innerProcessResult(WARCWriterProcessor.java:195)
        at org.archive.modules.Processor.process(Processor.java:142)
        at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
        at org.archive.crawler.framework.ToeThread.run(ToeThread.java:152)
 java.lang.NullPointerException
        at org.archive.io.warc.WARCWriter.getFilenameWithoutOccupiedSuffix(WARCWriter.java:275)
        at org.archive.modules.writer.WARCWriterProcessor.updateMetadataAfterWrite(WARCWriterProcessor.java:289)
        at org.archive.modules.writer.WARCWriterProcessor.write(WARCWriterProcessor.java:259)
        at org.archive.modules.writer.WARCWriterProcessor.innerProcessResult(WARCWriterProcessor.java:195)
        at org.archive.modules.Processor.process(Processor.java:142)
        at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
        at org.archive.crawler.framework.ToeThread.run(ToeThread.java:152)
2016-08-12T09:06:35.098Z    -5         52 dns:wiki.bl.uk P https://wiki.bl.uk:8443/ text/dns #002 20160812090633536+66 sha1:KHNVONKMAARJYO2OZHRC2TPPZZM6A7AG - err=java.lang.NullPointerException
 java.lang.NullPointerException
        at org.archive.io.warc.WARCWriter.getFilenameWithoutOccupiedSuffix(WARCWriter.java:275)
        at org.archive.modules.writer.WARCWriterProcessor.updateMetadataAfterWrite(WARCWriterProcessor.java:289)
        at org.archive.modules.writer.WARCWriterProcessor.write(WARCWriterProcessor.java:259)
        at org.archive.modules.writer.WARCWriterProcessor.innerProcessResult(WARCWriterProcessor.java:195)
        at org.archive.modules.Processor.process(Processor.java:142)
        at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
        at org.archive.crawler.framework.ToeThread.run(ToeThread.java:152)
 java.lang.NullPointerException
        at org.archive.io.warc.WARCWriter.getFilenameWithoutOccupiedSuffix(WARCWriter.java:275)
        at org.archive.modules.writer.WARCWriterProcessor.updateMetadataAfterWrite(WARCWriterProcessor.java:289)
        at org.archive.modules.writer.WARCWriterProcessor.write(WARCWriterProcessor.java:259)
        at org.archive.modules.writer.WARCWriterProcessor.innerProcessResult(WARCWriterProcessor.java:195)
        at org.archive.modules.Processor.process(Processor.java:142)
        at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
        at org.archive.crawler.framework.ToeThread.run(ToeThread.java:152)
```

Any ideas what's going awry here? Seems like a race-condition when setting up the WARC writers?

**Comment by nlevitt** [comment]
Thanks for reporting @anjackson. Here is a fix: https://github.com/internetarchive/heritrix3/pull/168

The issue doesn't happen if you have `poolMaxActive=1` which I think is why I hadn't seen it. Not sure why it hasn't been happening for a long time though (not that I really investigated).

I was seeing the stack trace below. The problem was multiple threads trying to create the "warcs" directory at the same time. Fix was to synchronize around the directory creation.
```
java.io.IOException: Failed to create directory: /1/ait-h3-jobs/gh-167/20160815201316/warcs
	at org.archive.util.FileUtils.ensureWriteableDirectory(FileUtils.java:677)
	at org.archive.modules.writer.WriterPoolProcessor.calcOutputDirs(WriterPoolProcessor.java:457)
	at org.archive.io.WriterPoolMember.createFile(WriterPoolMember.java:203)
	at org.archive.io.WriterPoolMember.checkSize(WriterPoolMember.java:180)
	at org.archive.modules.writer.WARCWriterProcessor.write(WARCWriterProcessor.java:219)
	at org.archive.modules.writer.WARCWriterProcessor.innerProcessResult(WARCWriterProcessor.java:195)
	at org.archive.modules.Processor.process(Processor.java:142)
	at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
	at org.archive.crawler.framework.ToeThread.run(ToeThread.java:152)
2016-08-15 20:13:18.793 SEVERE thread-56 org.archive.crawler.framework.ToeThread.recoverableProblem() Problem java.lang.NullPointerException occured when trying to process 'dns:archive.org' at step ABOUT_TO_BEGIN_PROCESSOR in 

java.lang.NullPointerException
	at org.archive.io.warc.WARCWriter.getFilenameWithoutOccupiedSuffix(WARCWriter.java:274)
	at org.archive.modules.writer.WARCWriterProcessor.updateMetadataAfterWrite(WARCWriterProcessor.java:289)
	at org.archive.modules.writer.WARCWriterProcessor.write(WARCWriterProcessor.java:259)
	at org.archive.modules.writer.WARCWriterProcessor.innerProcessResult(WARCWriterProcessor.java:195)
	at org.archive.modules.Processor.process(Processor.java:142)
	at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
	at org.archive.crawler.framework.ToeThread.run(ToeThread.java:152)
```

**Comment by anjackson** [comment]
Thanks @nlevitt - I'll test it ASAP but it might be a little while yet.

**Comment by nlevitt** [comment]
Merged anyhow
