### ISSUE TITLE
Possibly stalled crawl

### ISSUE THREAD

**Issue by mtcjayne** [internetarchive/heritrix3#203]
I have a job that looks like it has stalled out, and I'm not sure why.

I am running Heritrix 3.1.1 on Debian 9.

Here are some stats from the job web page:
```
Job is Active: RUNNING
Totals
4403 downloaded + 16788 queued = 21191 total
241 MiB crawled (241 MiB novel, 0 B dupByHash, 0 B notModified)
Alerts
31 tail alert log...
Rates
0 URIs/sec (0.16 avg); 0 KB/sec (8 avg)
Load
0 active of 2 threads; 1 congestion ratio; 16785 deepest queue; 4197 average depth
Elapsed
7h50m16s124ms
Threads
2 threads: 2 ABOUT_TO_GET_URI; 2 noActiveProcessor 
Frontier
RUN - 33 URI queues: 4 active (0 in-process; 0 ready; 4 snoozed); 0 inactive; 0 ineligible; 0 retired; 29 exhausted 
Memory
82250 KiB used; 131320 KiB current heap; 253440 KiB max heap
```
Pastebin of the job log: https://pastebin.com/raw/nYj0mVDy

**Comment by mtcjayne** [comment]
On the [previous issue over at iipc/openwayback](https://github.com/iipc/openwayback/issues/376) @nlevitt had mentioned:

> Those SEVERE errors look suspicious
> `2018-04-24T02:25:34.762Z SEVERE close() ros[ToeThread #16: https://i.warosu.org/robots.txt`
> Maybe one of the error logs (nonfatal-errors.log, runtime-errors.log or alerts.log), or heritrix_out.log, has more info about that, like a stack trace?

Here are those logs:
[nonfatal-errors.log](https://github.com/internetarchive/heritrix3/files/1944376/nonfatal-errors.log)
runtime-errors.log was empty
[alerts.log](https://github.com/internetarchive/heritrix3/files/1944380/alerts.log)

There are stack traces in alerts.log.

**Comment by mtcjayne** [comment]
After checkpointing and changing the referrer I've found the crawl is now moving along again. I don't know if that's a coincidence, but I'd left it running the entire time and it had gone from 4403 to 4411 in over 36 hours

**Comment by mtcjayne** [comment]
```
2018-04-29T03:03:46.191Z    -2          0 https://api.flattr.com/robots.txt LEPR http://api.flattr.com/robots.txt unknown #011 - - - -
 java.io.IOException: ROS already open for ToeThread #11: https://api.flattr.com/robots.txt
	at org.archive.io.RecordingOutputStream.open(RecordingOutputStream.java:181)
	at org.archive.util.Recorder.outputWrap(Recorder.java:203)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:760)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	at org.archive.modules.fetcher.FetchHTTP.innerProcess(FetchHTTP.java:646)
	at org.archive.modules.Processor.innerProcessResult(Processor.java:175)
	at org.archive.modules.Processor.process(Processor.java:142)
	at org.archive.modules.fetcher.FetchHTTP.process(FetchHTTP.java:905)
	at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
	at org.archive.crawler.framework.ToeThread.run(ToeThread.java:147)
 java.io.IOException: ROS already open for ToeThread #11: https://api.flattr.com/robots.txt
	at org.archive.io.RecordingOutputStream.open(RecordingOutputStream.java:181)
	at org.archive.util.Recorder.outputWrap(Recorder.java:203)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:760)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:346)
	at org.archive.modules.fetcher.FetchHTTP.innerProcess(FetchHTTP.java:646)
	at org.archive.modules.Processor.innerProcessResult(Processor.java:175)
	at org.archive.modules.Processor.process(Processor.java:142)
	at org.archive.modules.fetcher.FetchHTTP.process(FetchHTTP.java:905)
	at org.archive.modules.ProcessorChain.process(ProcessorChain.java:131)
	at org.archive.crawler.framework.ToeThread.run(ToeThread.java:147)
```
https://webarchive.jira.com/browse/HER-1172 references this issue. Can someone try using the seed `http://erdgeist.org` with 3.1.1. and see if they have the same result? This happens within seconds. I'm trying to identify if this is Heritrix or the environment I'm running it in.

**Comment by nlevitt** [comment]
I don't have 3.1.1 handy but the problem doesn't happen for me on HEAD. 

Why are you using such an old version? 3.2.0 was released in 2014. 

Since then we haven't put out any official releases, but there have been a lot of bug fixes. I would use the latest build:
http://builds.archive.org/maven2/org/archive/heritrix/heritrix/3.3.0-SNAPSHOT/heritrix-3.3.0-SNAPSHOT-dist.tar.gz

**Comment by mtcjayne** [comment]
Thanks for the response, I've been using 3.2.0 and am seeing the same error messages. I'll try a snapshot too.

**Comment by mtcjayne** [comment]
I can't even get 3.3.0-SNAPSHOT (January 25th build) to start so I'll try again next snapshot.

**Comment by mtcjayne** [comment]
Can't even go back to 3.2.0 now, no clue why.

With 3.2.0
```
Tue May  1 13:32:21 CDT 2018 Starting heritrix
Linux mtcserver 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~deb9u1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
JAVA_OPTS= -Xmx256m
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15735
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 15735
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
Oracle Corporation OpenJDK Runtime Environment 1.8.0_171-8u171-b11-1~deb9u1-b11
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at org.archive.crawler.Heritrix.instanceMain(Heritrix.java:312)
        at org.archive.crawler.Heritrix.main(Heritrix.java:189)
```
With 3.3.0-SNAPSHOT (January 25th build) I get the same output with the exception of the exception starting one line earlier since a line was added to the file before it.
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
        at org.archive.crawler.Heritrix.instanceMain(Heritrix.java:311)
        at org.archive.crawler.Heritrix.main(Heritrix.java:188)
```

**Comment by mtcjayne** [comment]
I do not see the error messages on the most recent (as of now January 25, 2018) snapshot of 3.3.0.

**Comment by nlevitt** [comment]
😁😁😁😁
