### ISSUE TITLE
Error Binding hostname or ip to Web UI

### ISSUE THREAD

**Issue by tchnlgst** [internetarchive/heritrix3#339]
I can't seem to bind an ip or hostname to the Web UI. Heritrix aborts starting with the following:

Exception in thread "main" java.io.IOException: Failed to bind to x.x.x.x:8443
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:346)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:308)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:396)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.restlet.ext.jetty.JettyServerHelper.start(JettyServerHelper.java:707)
	at org.restlet.Server.start(Server.java:579)
	at org.restlet.Component.startServers(Component.java:642)
	at org.restlet.Component.start(Component.java:567)
	at org.archive.crawler.Heritrix.instanceMain(Heritrix.java:358)
	at org.archive.crawler.Heritrix.main(Heritrix.java:184)
Caused by: java.net.BindException: Cannot assign requested address
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:220)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:85)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:342)

I'd appreciate any guidance on this.

**Comment by tchnlgst** [comment]
an update on this. 

As this is a host running on an AWS EC-2 instance, I was using the public hostname for binding.

The instance runs within a VPC. I got around the error and resolved the issue by adding an /etc/hosts entry pointing the private vpc ip to the public hostname.

**Comment by ato** [comment]
Yep, Linux only allows applications to bind to IP addresses that a network interface on host is actually configured with¹. That is, the addresses that are listed if you run 'ip addr'. In the case where there's a layer like vpc or some sort of proxy or load balancer passing the traffic to a private address then indeed the appropriate address to bind to is indeed the private one.

--
¹ Technically there's a kernel option to allow applications to bind to any random address but that wouldn't help you in this situation as when packets come into the host they are addressed to the private ip not the public ip.
