### ISSUE TITLE
Thread-safely issues with the CookieStore

### ISSUE THREAD

**Issue by anjackson** [internetarchive/heritrix3#427]
I'm using [the 3.4.0-20210803 release](https://github.com/internetarchive/heritrix3/releases/tag/3.4.0-20210803) for a domain crawl.

That version [includes changes in the CookieStore](https://github.com/internetarchive/heritrix3/pull/397), and I'm seeing failures under load.

These are due to a `Cookie cookie` variable being `null`.

```
SEVERE: Problem java.lang.NullPointerException occurred when trying to process 'https://www.library.wales/robots.txt' at step ABOUT_TO_BEGIN_PROCESSOR in

java.lang.NullPointerException
        at org.archive.modules.fetcher.AbstractCookieStore.sortableKey(AbstractCookieStore.java:260)
        at org.archive.modules.fetcher.BdbCookieStore.expireCookie(BdbCookieStore.java:145)
        at org.archive.modules.fetcher.AbstractCookieStore$LimitedCookieStoreFacade.clearExpired(AbstractCookieStore.java:229)
        at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:183)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
```

```
SEVERE: Problem java.lang.NullPointerException occurred when trying to process 'https://search.nls.uk/robots.txt' at step ABOUT_TO_BEGIN_PROCESSOR in

java.lang.NullPointerException
        at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:165)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.archive.modules.fetcher.FetchHTTPRequest.execute(FetchHTTPRequest.java:752)
        at org.archive.modules.fetcher.FetchHTTP.innerProcess(FetchHTTP.java:658)
        at org.archive.modules.Processor.innerProcessResult(Processor.java:175)
        at org.archive.modules.Processor.process(Processor.java:142)
```

...and I'm also seeing...

```
SEVERE: Problem java.lang.ArrayIndexOutOfBoundsException: 6 occurred when trying to process 'http://www.adamcopitch.co.uk/?page_id=6' at step ABOUT_TO_BEGIN_PROCESSOR in

java.lang.ArrayIndexOutOfBoundsException: 6
        at org.apache.commons.collections.collection.CompositeCollection.toArray(CompositeCollection.java:159)
        at org.archive.modules.fetcher.BdbCookieStore$RestrictedCollectionWrappedList.iterator(BdbCookieStore.java:78)
        at org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:164)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:133)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.archive.modules.fetcher.FetchHTTPRequest.execute(FetchHTTPRequest.java:752)
        at org.archive.modules.fetcher.FetchHTTP.innerProcess(FetchHTTP.java:658)
```

This last one seems very likely to be a problem arising because the `CompositeCollection` is not thread safe.  All usage needs to be synchronised, which likely makes the cookie management a global bottleneck.  There does not appear to be a thread-safe implementation available.

The set of cookies for each host or domain should generally be handled separately, so perhaps this specific problem is arising when processing seeds that are on different hosts on the same domain? __EDIT__ it seems not as the crawl index indicates the crawler only visited `www.adamcopitch.co.uk` and not any other subdomains, unless some other site managed to lodge a cookie at the `co.uk` or 'uk` level?

**Comment by ato** [comment]
Ah, indeed, CompositeCollection.toArray() will fail if the composed collections change size. Returning nulls if they shrink or throwing ArrayIndexOutOfBoundsException if they grow. It looks like iterator() should be safe though.

I'm a little confused why RestrictedCollectionWrappedList.iterator() calls `wrapped.toArray()` instead of just  `wrapped.iterator()`. I think something like this would make it safe in the face of the collections changing size:

```java
@Override public Iterator<T> iterator() { return wrapped.iterator(); }
@Override public Object[] toArray() { return IteratorUtils.toArray(wrapped.iterator()); }
@SuppressWarnings({"hiding", "unchecked"}) @Override public <T> T[] toArray(T[] a) { return (T[]) IteratorUtils.toArray(iterator(), a.getClass()); }
```
